### PR TITLE
Build the Website Home Page #1

### PR DESCRIPTION
**Pull request by dilini-liyanage**
Build the Website Home Page #1

### CODE REVIEW

**Comment by loan-mgt** [comment]
😭😭 I am so sorry I didn't give you the assets,
The font is Poppins 
I get back to you sone with the svg assets

**Comment by loan-mgt** [comment]
Here you go

Background 
background
Logo
logo
Arrow
arrow

**Comment by dilini-liyanage** [comment]
Sure , I will use those assets and update the code

**Review by loan-mgt — APPROVED** [review]

**Comment by loan-mgt** [comment]
thanks 👍

**Pull request merged**
